//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KafkaProducer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashiersRole
    {
        public int Id { get; set; }
        public string Shop { get; set; }
        public Nullable<int> CodeRole { get; set; }
        public string NameRole { get; set; }
        public System.DateTime InsDt { get; set; }
        public string System_User { get; set; }
    }
}
