//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KafkaProducer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetXml
    {
        public int Id { get; set; }
        public string XmlText { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public string InsUser { get; set; }
        public string Adress { get; set; }
        public string Port { get; set; }
        public string Topic { get; set; }
    }
}
