//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KafkaProducer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KafkaJobEntities : DbContext
    {
        public KafkaJobEntities()
            : base("name=KafkaJobEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cashiers> Cashiers { get; set; }
        public virtual DbSet<CashiersRole> CashiersRole { get; set; }
        public virtual DbSet<GetXml> GetXml { get; set; }
        public virtual DbSet<Config> Config { get; set; }
        public virtual DbSet<SetXml> SetXml { get; set; }
    }
}
